export const dataCards = [
  {
    type: "hrest",
    img: "cards_hr.png",
    cards_name: [
      { name: "tuz", strong: 14, pos_img: "-71px -8px" },
      { name: "korol", strong: 13, pos_img: "-209px -8px" },
      { name: "dama", strong: 12, pos_img: "-350px -8px" },
      { name: "valet", strong: 11, pos_img: "-493px -8px" },
      { name: "ten", strong: 10, pos_img: "-10px -211px" },
      { name: "nine", strong: 9, pos_img: "-147px -211px" },
      { name: "eight", strong: 8, pos_img: "-289px -211px" },
      { name: "seven", strong: 7, pos_img: "-431px -211px" },
      { name: "six", strong: 6, pos_img: "-568px -211px" },
    ],
  },
  {
    type: "pika",
    img: "cards_pk.png",
    cards_name: [
      { name: "tuz", strong: 14, pos_img: "-65px -13px" },
      { name: "korol", strong: 13, pos_img: "-204px -13px" },
      { name: "dama", strong: 12, pos_img: "-348px -13px" },
      { name: "valet", strong: 11, pos_img: "-492px -13px" },
      { name: "ten", strong: 10, pos_img: "-5px -207px" },
      { name: "nine", strong: 9, pos_img: "-145px -207px" },
      { name: "eight", strong: 8, pos_img: "-288px -207px" },
      { name: "seven", strong: 7, pos_img: "-423px -207px" },
      { name: "six", strong: 6, pos_img: "-562px -207px" },
    ],
  },
  {
    type: "cherv",
    img: "cards_ch.png",
    cards_name: [
      { name: "tuz", strong: 14, pos_img: "-549px -23px" },
      { name: "korol", strong: 13, pos_img: "-156px -23px" },
      { name: "dama", strong: 12, pos_img: "-286px -23px" },
      { name: "valet", strong: 11, pos_img: "-419px -23px" },
      { name: "ten", strong: 10, pos_img: "-550px 202px" },
      { name: "nine", strong: 9, pos_img: "-419px -405px" },
      { name: "eight", strong: 8, pos_img: "-286px -406px" },
      { name: "seven", strong: 7, pos_img: "-155px -405px" },
      { name: "six", strong: 6, pos_img: "-21px -405px" },
    ],
  },
  {
    type: "bubna",
    img: "cards_bn.png",
    cards_name: [
      { name: "tuz", strong: 14, pos_img: "-55px -25px" },
      { name: "korol", strong: 13, pos_img: "-479px -25px" },
      { name: "dama", strong: 12, pos_img: "-329px -25px" },
      { name: "valet", strong: 11, pos_img: "-190px -25px" },
      { name: "ten", strong: 10, pos_img: "-27px -221px" },
      { name: "nine", strong: 9, pos_img: "-156px -221px" },
      { name: "eight", strong: 8, pos_img: "-292px -221px" },
      { name: "seven", strong: 7, pos_img: "-420px -221px" },
      { name: "six", strong: 6, pos_img: "-559px -221px" },
    ],
  },
];
